import type { Metadata } from "next";
import "./globals.css";
import { getServerSession, Session } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";
import SessionWrapper from "./components/common/SessionWrapper/page";
import { Kiwi_Maru } from "next/font/google";
import { ThemeProviderWrapper } from "./components/common/ThemeProviderWrapper/page";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const kiwiMaru = Kiwi_Maru({
  subsets: ["latin"],
  weight: "300",
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <SessionWrapper session={session as Session}>
      <ThemeProviderWrapper>
        <html lang="ja">
          <body className={kiwiMaru.className}>{children}</body>
        </html>
      </ThemeProviderWrapper>
    </SessionWrapper>
  );
}
