import type { Metadata } from "next";
import "./globals.css";
import { getServerSession, Session } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";
import SessionWrapper from "./components/SessionWrapper/page";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <SessionWrapper session={session}>
      <html lang="ja">
        <body>
          <body>{children}</body>
        </body>
      </html>
    </SessionWrapper>
  );
}
